# Generated by Django 4.1.4 on 2022-12-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_profile_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facts', models.IntegerField()),
                ('facts', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.fact')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
