# Generated by Django 4.1.4 on 2022-12-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='id',
        ),
        migrations.AlterField(
            model_name='fact',
            name='id_facts',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_facts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.fact'),
        ),
    ]
