# Generated by Django 4.1.4 on 2022-12-26 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_favoritos_delete_user_remove_fact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='id_facts',
        ),
        migrations.AddField(
            model_name='fact',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fact',
            name='id_facts',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
