version: '3.9' # https://github.com/compose-spec/compose-spec/blob/master/spec.md


services:
  app: 
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
